USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE ELT_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = TRUE;

GRANT ALL ON WAREHOUSE ELT_WH TO ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE POWERBI_WH
  WITH WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = TRUE;

GRANT ALL ON WAREHOUSE POWERBI_WH TO ROLE SYSADMIN;

CREATE OR REPLACE ROLE POWERBI_ROLE COMMENT='Power BI Role';
GRANT ALL ON WAREHOUSE POWERBI_WH TO ROLE POWERBI_ROLE;
GRANT ROLE POWERBI_ROLE TO ROLE SYSADMIN;

CREATE OR REPLACE USER POWERBI PASSWORD='PBISF123' 
    DEFAULT_ROLE=POWERBI_ROLE 
    DEFAULT_WAREHOUSE=POWERBI_WH
    DEFAULT_NAMESPACE=LAB_DW.PUBLIC
    COMMENT='Power BI User';

GRANT ROLE POWERBI_ROLE TO USER POWERBI;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS LAB_DB;

GRANT USAGE ON DATABASE LAB_DB TO ROLE POWERBI_ROLE;


USE LAB_DB.PUBLIC;
USE WAREHOUSE ELT_WH;


CREATE OR REPLACE TABLE CATEGORY (
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE CHANNELS (
	CHANNEL_ID NUMBER(38,0),
	CHANNEL_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE DEPARTMENT (
	DEPARTMENT_ID NUMBER(38,0),
	DEPARTMENT_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE ITEMS (
	ITEM_ID NUMBER(38,0),
	ITEM_NAME VARCHAR(250),
	ITEM_PRICE FLOAT,
	DEPARTMENT_ID NUMBER(38,0),
	CATEGORY_ID NUMBER(38,0),
	TMP_ITEM_ID NUMBER(38,0)
);

CREATE OR REPLACE TABLE SALES_ORDERS (
	SALES_ORDER_ID NUMBER(38,0),
	CHANNEL_CODE NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	PAYMENT_ID NUMBER(38,0),
	EMPLOYEE_ID NUMBER(38,0),
	LOCATION_ID NUMBER(38,0),
	SALES_DATE TIMESTAMP_NTZ(9),
	TMP_ORDER_ID FLOAT,
	TMP_ORDER_DOW NUMBER(38,0),
	TMP_USER_ID NUMBER(38,0)
);


CREATE OR REPLACE TABLE ITEMS_IN_SALES_ORDERS (
	SALES_ORDER_ID NUMBER(38,0),
	ITEM_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	PROMOTION_ID NUMBER(38,0),
	QUANTITY FLOAT,
	REORDERED NUMBER(38,0),
	TMP_ORDER_ID FLOAT,
	TMP_PRODUCT_ID NUMBER(38,0)
);

CREATE OR REPLACE TABLE LOCATIONS (
	LOCATION_ID NUMBER(38,0),
	NAME VARCHAR(100),
	GEO2 VARCHAR(250),
	GEO GEOGRAPHY,
	LAT FLOAT,
	LONG FLOAT,
	COUNTRY VARCHAR(200),
	REGION VARCHAR(100),
	MUNICIPALITY VARCHAR(200),
	LONGITUDE FLOAT,
	LATITUDE FLOAT
);

CREATE OR REPLACE TABLE STATES (
	STATE_CODE NUMBER(38,0),
	STATE_NAME VARCHAR(250),
	REGION VARCHAR(250),
	STATE_GEO VARCHAR(16777216)
);


GRANT USAGE ON SCHEMA LAB_DB.PUBLIC TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA LAB_DB.PUBLIC TO ROLE POWERBI_ROLE;


CREATE OR REPLACE STAGE LAB_DATA_STAGE 
url='azure://ab12345lab2.blob.core.windows.net/labdata'
credentials=(azure_sas_token='sp=r&st=2026-02-04T20:32:29Z&se=2026-02-11T04:47:29Z&spr=https&sv=2024-11-04&sr=c&sig=xW8%2F0EF30Le18T5bRCwkZaKZo1JrndAV5ZXHSkG7070%3D');
--https://ab12345lab2.blob.core.windows.net/?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-02-11T05:55:46Z&st=2026-02-04T21:40:46Z&spr=https&sig=VbkWasc4r7TCCU6NEZRDMHNNZdqx4MXYIB%2FsIErra%2B8%3D


CREATE OR REPLACE STAGE LAB_DATA_STAGE 
URL='azure://ab12345lab2.blob.core.windows.net/labdata'
CREDENTIALS=(AZURE_SAS_TOKEN='sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-02-11T05:02:28Z&st=2026-02-04T20:47:28Z&spr=https&sig=kxauEagwkVwS20UwbNO0BlvLPhxXwNHgaTs8NtTtPj0%3D');

-- Test it immediately:
LIST @LAB_DATA_STAGE;


CREATE OR REPLACE FILE FORMAT CSVNOHEADER
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
    NULL_IF = ('NULL');

LIST @LAB_DATA_STAGE;

-- 1. Create a table to hold the data
CREATE OR REPLACE TABLE LAB_SALES_DATA (
    ORDER_ID STRING,
    ITEM_NAME STRING,
    QUANTITY NUMBER,
    PRICE NUMBER,
    ORDER_DATE DATE
);

-- 2. Pull the data from the stage into the table
COPY INTO LAB_SALES_DATA
FROM @LAB_DATA_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

-- 3. Verify the data is there
SELECT * FROM LAB_SALES_DATA LIMIT 10;

COPY INTO CATEGORY FROM @LAB_DATA_STAGE/category/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);

SELECT * FROM CATEGORY LIMIT 100;

COPY INTO CHANNELS FROM @LAB_DATA_STAGE/channels/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);
SELECT * FROM CHANNELS LIMIT 100;

COPY INTO DEPARTMENT from @LAB_DATA_STAGE/department/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);
SELECT * FROM DEPARTMENT LIMIT 100;

COPY INTO ITEMS from @LAB_DATA_STAGE/items/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);
SELECT * FROM ITEMS LIMIT 100;

COPY INTO LOCATIONS from @LAB_DATA_STAGE/locations/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);
SELECT * FROM LOCATIONS LIMIT 100;

COPY INTO STATES from @LAB_DATA_STAGE/states/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);
SELECT * FROM STATES LIMIT 100;

LIST @LAB_DATA_STAGE/items_in_sales_orders/;

COPY INTO ITEMS_IN_SALES_ORDERS from @LAB_DATA_STAGE/items_in_sales_orders/items_in_sales_orders_0_0_0.csv.gz FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);





ALTER WAREHOUSE ELT_WH SET WAREHOUSE_SIZE = 'X-LARGE';

COPY INTO ITEMS_IN_SALES_ORDERS from   @LAB_DATA_STAGE/items_in_sales_orders/ 
FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);

COPY INTO SALES_ORDERS from @lab_data_stage/sales_orders/ FILE_FORMAT = (FORMAT_NAME = CSVNOHEADER);

ALTER WAREHOUSE ELT_WH SET WAREHOUSE_SIZE = 'x-small' ;


SELECT COUNT(*) AS SALES_ORDERS_COUNT FROM SALES_ORDERS;

SELECT * FROM DEPARTMENT where department_id = 39;

SELECT 
  DEPARTMENT_ID
  ,COUNT(*) AS REC_COUNT
FROM PUBLIC.DEPARTMENT
GROUP BY 1
ORDER BY 2 DESC;


SELECT REGION FROM STATES;

SELECT REGION FROM LOCATIONS;

CREATE OR REPLACE VIEW PUBLIC.LOCATION_V AS
SELECT
  L.LOCATION_ID,
  L.COUNTRY,
  L.REGION,
  L.MUNICIPALITY,
  S.STATE_NAME,
  S.STATE_GEO,
  L.LONGITUDE,
  L.LATITUDE
FROM LOCATIONS L
    INNER JOIN STATES S ON L.REGION = S.REGION;


CREATE OR REPLACE VIEW PUBLIC.ITEMS_V AS
SELECT 
  ITEM_ID,
  ITEM_NAME,
  ITEM_PRICE,
  CATEGORY_NAME,
  DEPARTMENT_NAME
FROM ITEMS I
    INNER JOIN DEPARTMENT D ON I.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN CATEGORY C ON I.CATEGORY_ID = C.CATEGORY_ID
WHERE I.DEPARTMENT_ID != 39;

CREATE OR REPLACE VIEW PUBLIC.SALES_ORDERS_V AS
SELECT
  S.ITEM_ID,
  S.QUANTITY,
  SO.CHANNEL_CODE,
  SO.LOCATION_ID,
  SO.SALES_DATE,
  S.ORDER_ID
FROM ITEMS_IN_SALES_ORDERS S
    INNER JOIN SALES_ORDERS SO ON S.ORDER_ID = SO.SALES_ORDER_ID;


CREATE OR REPLACE VIEW PUBLIC.SALES_ORDERS_V_AGG AS
SELECT
  ITEM_ID,
  CHANNEL_CODE AS CHANNEL_ID,
  LOCATION_ID,
  SUM(QUANTITY) TOTAL_QUANTITY
FROM PUBLIC.SALES_ORDERS_V
GROUP BY
  ITEM_ID,
  CHANNEL_CODE,
  LOCATION_ID;


-- Scale back down to X-SMALL for the views and analysis
ALTER WAREHOUSE ELT_WH SET WAREHOUSE_SIZE = 'X-SMALL';

-- Get your Server/Account URL
SELECT CURRENT_ACCOUNT_URL(); 

-- Get your Current User
SELECT CURRENT_USER();

-- Get your Current Warehouse
SELECT CURRENT_WAREHOUSE();

-- Get your Current Role
SELECT CURRENT_ROLE();

USE ROLE ACCOUNTADMIN;
ALTER USER POWERBI SET DISABLE_MFA = TRUE;
USE ROLE ACCOUNTADMIN;
USE ROLE ACCOUNTADMIN;



  USE ROLE ACCOUNTADMIN;

-- This reset ensures we know EXACTLY what the password is
ALTER USER POWERBI SET 
  PASSWORD = 'PowerBI_AVas_2026!'
  DISABLE_MFA = TRUE
  MINS_TO_UNLOCK = 0;

  USE ROLE ACCOUNTADMIN;
SHOW USERS LIKE 'POWERBI';

CREATE OR REPLACE VIEW PUBLIC.SALES_ORDERS_V AS
SELECT
  S.ITEM_ID,
  S.QUANTITY,
  SO.CHANNEL_CODE,
  SO.LOCATION_ID,
  SO.SALES_DATE,
  S.ORDER_ID
ITEMS_IN_SALES_ORDERS S
    INNER JOIN SALES_ORDERS SO ON S.ORDER_ID = SO.SALES_ORDER_ID;

SELECT
  ITEM_ID,
  QUANTITY,
  CHANNEL_CODE,
  LOCATION_ID,
  SALES_DATE,
  ORDER_ID
FROM PUBLIC.SALES_ORDERS_V 
LIMIT 100;

SELECT current_account() || '.' || current_region() || '.snowflakecomputing.com';

-- Replace 'your_email@example.com' with the email you use to sign into Microsoft
GRANT ROLE POWERBI_ROLE TO USER "AdrianVasquez@geralleads.onmicrosoft.com";

USE ROLE ACCOUNTADMIN;
ALTER USER "POWERBI" SET DISABLE_MFA = TRUE;

USE ROLE ACCOUNTADMIN;

-- 1. Force recreate the user with the exact password
CREATE OR REPLACE USER POWERBI 
  PASSWORD = 'PowerBI_AV_2026!'
  DEFAULT_ROLE = 'POWERBI_ROLE'
  DEFAULT_WAREHOUSE = 'POWERBI_WH'
  MUST_CHANGE_PASSWORD = FALSE;

-- 2. Make sure the role exists and the user has it
CREATE ROLE IF NOT EXISTS POWERBI_ROLE;
GRANT ROLE POWERBI_ROLE TO USER POWERBI;
GRANT ROLE POWERBI_ROLE TO ROLE SYSADMIN;

-- 3. Give the role access to your data
GRANT USAGE ON DATABASE LAB_DB TO ROLE POWERBI_ROLE;
GRANT USAGE ON SCHEMA LAB_DB.PUBLIC TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA LAB_DB.PUBLIC TO ROLE POWERBI_ROLE;
GRANT USAGE ON WAREHOUSE POWERBI_WH TO ROLE POWERBI_ROLE;

USE ROLE ACCOUNTADMIN;

-- This disables the MFA requirement for your bot account
ALTER USER POWERBI SET DISABLE_MFA = TRUE;

-- Optional: If you are using your personal email account to log in, 
-- run it for your email too (replace with your email):
ALTER USER "AdrianVasquez@geralleads.onmicrosoft.com" SET DISABLE_MFA = TRUE;
ALTER USER POWERBI SET MINS_TO_BYPASS_MFA = 10080;